site_name: Ling Han's Blog
site_url: 

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: cyan
  features:
    - navigation.tabs
    - toc.integrate
  language: zh

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format